# .github/workflows/build_and_publish.yml

name: Build and Publish to NPM
on: [push]

# by default, permissions are read-only, read + write is required for git pushes
permissions:
  contents: write

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"

      - name: Install Dependencies
        run: npm ci

      - name: Run Test
        run: npm test

  build-and-publish:
    runs-on: ubuntu-latest
    needs: matrix-test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ASDF Parse
        uses: kota65535/github-asdf-parse-action@v1
        id: versions

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.versions.outputs.nodejs }}"
          registry-url: "https://registry.npmjs.org"

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./package.json,./package-lock.json"
          output-file: "CHANGELOG.md"

      - name: Publish to NPM
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm publish
        env:
          # `gh secret set NPM_TOKEN --app actions --body $NPM_TOKEN`
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Github Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v1
        with:
          # output options: https://github.com/TriPSs/conventional-changelog-action#outputs
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
